# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stephentudor.com
title: The Tude Abides
permalink: /blog/:year/:month/:day/:title
subtitle: A personal log of front-end developer Stephen Tudor
author: Stephen Tudor
simple_search: http://google.com/search

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
port: 4000
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: kramdown
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10 # Posts per page on the blog index
recent_posts: 5 # Posts in the sidebar Recent Posts section

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [custom/asides/about.html, asides/recent_posts.html, asides/twitter.html, asides/pinboard.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
#blog_index_asides: [custom/asides/about.html, asides/recent_posts.html, asides/twitter.html, asides/pinboard.html]
#post_asides: [custom/asides/about.html, asides/recent_posts.html, asides/twitter.html, asides/pinboard.html]
#page_asides: [custom/asides/about.html, asides/recent_posts.html, asides/twitter.html, asides/pinboard.html]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: tudorstudio
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google Plus
google_plus_one: true
google_plus_one_size: medium

# Pinboard
pinboard_user: smt
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: stephentudor

# Google Analytics
google_analytics_tracking_id: UA-545908-14
